// Code generated by protoc-gen-go. DO NOT EDIT.
// source: netrpc.proto

package netrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import "net/rpc"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// A request message
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a59f35d8fc3b423f, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// A response message
type HelloResponse struct {
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a59f35d8fc3b423f, []int{1}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// B response message
type HelloBye struct {
	Time                 int32    `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloBye) Reset()         { *m = HelloBye{} }
func (m *HelloBye) String() string { return proto.CompactTextString(m) }
func (*HelloBye) ProtoMessage()    {}
func (*HelloBye) Descriptor() ([]byte, []int) {
	return fileDescriptor_a59f35d8fc3b423f, []int{2}
}

func (m *HelloBye) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloBye.Unmarshal(m, b)
}
func (m *HelloBye) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloBye.Marshal(b, m, deterministic)
}
func (m *HelloBye) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloBye.Merge(m, src)
}
func (m *HelloBye) XXX_Size() int {
	return xxx_messageInfo_HelloBye.Size(m)
}
func (m *HelloBye) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloBye.DiscardUnknown(m)
}

var xxx_messageInfo_HelloBye proto.InternalMessageInfo

func (m *HelloBye) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "netrpc.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "netrpc.HelloResponse")
	proto.RegisterType((*HelloBye)(nil), "netrpc.HelloBye")
}

func init() { proto.RegisterFile("netrpc.proto", fileDescriptor_a59f35d8fc3b423f) }

var fileDescriptor_a59f35d8fc3b423f = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0x4b, 0x2d, 0x29,
	0x2a, 0x48, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x94, 0xb8, 0x78,
	0x3c, 0x52, 0x73, 0x72, 0xf2, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x84, 0xb8, 0x58,
	0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25, 0x4d, 0x2e,
	0x5e, 0xa8, 0x9a, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x09, 0x2e, 0xf6, 0xdc, 0xd4, 0xe2,
	0xe2, 0xc4, 0xf4, 0x54, 0x09, 0x26, 0xb0, 0x3a, 0x18, 0x57, 0x49, 0x8e, 0x8b, 0x03, 0xac, 0xd4,
	0xa9, 0x32, 0x15, 0x64, 0x54, 0x49, 0x66, 0x6e, 0xaa, 0x04, 0xab, 0x02, 0xa3, 0x06, 0x6b, 0x10,
	0x98, 0x6d, 0xe4, 0xc4, 0xc5, 0xee, 0x5e, 0x94, 0x9a, 0x5a, 0x92, 0x5a, 0x24, 0x64, 0xce, 0xc5,
	0x11, 0x9c, 0x58, 0x09, 0x56, 0x2d, 0x24, 0xa2, 0x07, 0x75, 0x1c, 0xb2, 0x5b, 0xa4, 0x44, 0xd1,
	0x44, 0x21, 0xb6, 0x1b, 0x99, 0x73, 0x31, 0x83, 0x8c, 0x37, 0xe0, 0x62, 0x0b, 0x4e, 0xac, 0x04,
	0xb1, 0xb0, 0xeb, 0x16, 0x40, 0x11, 0x75, 0xaa, 0x4c, 0x75, 0xe2, 0x8e, 0xe2, 0xd4, 0xd3, 0xb7,
	0x86, 0x88, 0x26, 0xb1, 0x81, 0xc3, 0xc1, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x53, 0xb3,
	0x51, 0x17, 0x01, 0x00, 0x00,
}

// GreeterInterface 是 Greeter 服务的接口。
type GreeterInterface interface {
	SayHello(*HelloRequest, *HelloResponse) error
}

// RegisterGreeter 用于将服务注册到 rpc.Server。
func RegisterGreeter(
	srv *rpc.Server, x GreeterInterface,
) error {
	if err := srv.RegisterName("Greeter", x); err != nil {
		return err
	}
	return nil
}

// GreeterClient 是 Greeter 服务的客户端。
type GreeterClient struct {
	*rpc.Client
}

var _ GreeterInterface = (*GreeterClient)(nil)

// DialGreeter 用于创建 RPC 客户端。
func DialGreeter(network, address string) (
	*GreeterClient, error,
) {
	c, err := rpc.Dial(network, address)
	if err != nil {
		return nil, err
	}
	return &GreeterClient{Client: c}, nil
}

// SayHello 是客户端的远程调用方法。
func (p *GreeterClient) SayHello(
	in *HelloRequest, out *HelloResponse,
) error {
	return p.Client.Call("Greeter.SayHello", in, out)
}

// ByeInterface 是 Bye 服务的接口。
type ByeInterface interface {
	SayBye(*HelloRequest, *HelloBye) error
}

// RegisterBye 用于将服务注册到 rpc.Server。
func RegisterBye(
	srv *rpc.Server, x ByeInterface,
) error {
	if err := srv.RegisterName("Bye", x); err != nil {
		return err
	}
	return nil
}

// ByeClient 是 Bye 服务的客户端。
type ByeClient struct {
	*rpc.Client
}

var _ ByeInterface = (*ByeClient)(nil)

// DialBye 用于创建 RPC 客户端。
func DialBye(network, address string) (
	*ByeClient, error,
) {
	c, err := rpc.Dial(network, address)
	if err != nil {
		return nil, err
	}
	return &ByeClient{Client: c}, nil
}

// SayBye 是客户端的远程调用方法。
func (p *ByeClient) SayBye(
	in *HelloRequest, out *HelloBye,
) error {
	return p.Client.Call("Bye.SayBye", in, out)
}
